#!/usr/bin/env python3
"""Generate pytorch_auto_nodes.cpp from torchvision.transforms.functional."""

import argparse
import inspect
import sys
import typing


def _python_type_to_semantic(annotation) -> str | None:
    """Map a Python type annotation to a SemanticType string, or None to skip."""
    if annotation is inspect.Parameter.empty:
        return None

    origin = getattr(annotation, "__origin__", None)
    args = getattr(annotation, "__args__", ())

    # Optional[X] → unwrap
    if origin is typing.Union and len(args) == 2 and type(None) in args:
        inner = next(a for a in args if a is not type(None))
        return _python_type_to_semantic(inner)

    if annotation in (int,):
        return "Integer"
    if annotation in (float,):
        return "Float"
    if annotation in (bool,):
        return "Boolean"
    if annotation in (str,):
        return "String"

    return None


def _is_image_param(name: str, _annotation=None) -> bool:
    """Return True if this parameter represents the input image."""
    return name in ("img", "image", "tensor", "inpt")


def _collect_functions() -> list[dict]:
    try:
        import torchvision.transforms.functional as F  # noqa: PLC0415
    except ImportError:
        print("ERROR: torchvision is not installed. Install it with: pip install torchvision", file=sys.stderr)
        sys.exit(1)

    results = []
    for fn_name, fn in inspect.getmembers(F, inspect.isfunction):
        if fn_name.startswith("_"):
            continue

        sig = inspect.signature(fn)
        params = list(sig.parameters.values())
        if not params:
            continue

        # First param must be an image param
        if not _is_image_param(params[0].name, params[0].annotation):
            continue

        # Collect scalar params (skip image param and non-scalar types)
        scalar_params = []
        for p in params[1:]:
            if _is_image_param(p.name, p.annotation):
                continue
            semantic = _python_type_to_semantic(p.annotation)
            if semantic is None:
                continue
            default = p.default if p.default is not inspect.Parameter.empty else None
            scalar_params.append({
                "name": p.name,
                "semantic": semantic,
                "default": default,
                "required": p.default is inspect.Parameter.empty,
            })

        results.append({
            "fn_name": fn_name,
            "display_name": fn_name.replace("_", " ").title(),
            "scalar_params": scalar_params,
        })

    return results


_SEMANTIC_DEFAULTS = {
    "Integer": "0",
    "Float": "0.0",
    "Boolean": "false",
    "String": '""',
}


def _cpp_default(param: dict) -> str:
    val = param["default"]
    semantic = param["semantic"]
    if val is None:
        return _SEMANTIC_DEFAULTS.get(semantic, "0")
    if semantic == "Integer":
        return str(int(val))
    if semantic == "Float":
        return str(float(val))
    if semantic == "Boolean":
        return "true" if val else "false"
    if semantic == "String":
        return f'std::string("{val}")'
    return str(val)


def _generate_cpp(functions: list[dict]) -> str:
    lines = []
    lines.append("// AUTO-GENERATED by gen_nodes.py — do not edit")
    lines.append('#include "pytorch_helpers.hpp"')
    lines.append("#include \"cvhub/runtime/function_descriptor.hpp\"")
    lines.append("#include <unordered_map>")
    lines.append("")
    lines.append("namespace cvhub::plugins::pytorch {")
    lines.append("")

    factory_entries = []
    lines.append("std::vector<FunctionDescriptor> getAutoDescriptors()")
    lines.append("{")
    lines.append("    using namespace cvhub;")
    lines.append("    return {")

    for fn in functions:
        fn_name = fn["fn_name"]
        display = fn["display_name"]
        factory_key = f"pytorch.{fn_name}"

        lines.append("        FunctionDescriptor{")
        lines.append('            .library = "pytorch",')
        lines.append('            .namespaceName = "torchvision.transforms.functional",')
        lines.append(f'            .functionName = "{fn_name}",')
        lines.append(f'            .qualifiedName = "torchvision.transforms.functional.{fn_name}",')
        lines.append(f'            .displayName = "PyTorch {display}",')
        lines.append('            .category = "pytorch",')
        lines.append("            .arguments = {")
        lines.append(
            "                {.name = \"image\", .displayName = \"Image\","
            " .semanticType = SemanticType::Image, .direction = ArgumentDirection::Input},"
        )
        lines.append(
            "                {.name = \"image\", .displayName = \"Image\","
            " .semanticType = SemanticType::Image, .direction = ArgumentDirection::Output},"
        )

        for p in fn["scalar_params"]:
            semantic = f"SemanticType::{p['semantic']}"
            default_val = _cpp_default(p)
            required_str = "true" if p["required"] else "false"
            display_name = p["name"].replace("_", " ").title()
            lines.append(
                f'                {{.name = "{p["name"]}", .displayName = "{display_name}", '
                f'.semanticType = {semantic}, .direction = ArgumentDirection::Parameter, '
                f'.defaultValue = {default_val}, .required = {required_str}}},'
            )

        lines.append("            },")
        lines.append(f'            .factoryKey = "{factory_key}",')
        lines.append("            .explicitKind = NodeKind::Transform,")
        lines.append("        },")
        factory_entries.append(
            f'        {{"{factory_key}", [](NodeDescriptor descriptor) {{ '
            f'return makePythonTransformFactory(std::move(descriptor), "{fn_name}"); '
            f'}}}},'
        )

    lines.append("    };")
    lines.append("}")
    lines.append("")
    lines.append("std::unordered_map<std::string, FactoryFn> getAutoRegistry()")
    lines.append("{")
    lines.append("    return {")
    lines.extend(factory_entries)
    lines.append("    };")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace cvhub::plugins::pytorch")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate PyTorch plugin node descriptors")
    parser.add_argument("--output", required=True, help="Output .cpp file path")
    args = parser.parse_args()

    functions = _collect_functions()
    print(f"gen_nodes.py: found {len(functions)} torchvision functions", file=sys.stderr)

    cpp = _generate_cpp(functions)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(cpp)
    print(f"gen_nodes.py: wrote {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
